config/routes.rb
Sapphire::Application.routes.draw do
  #resources :feeditems , :only => [:new, :create]
  resources :userfeeds, :only => [:refresh_feed_list,:remove_feed,:show_feed_list,:mark_feed_viewed,
                                  :mark_feed_unread,:index,:destroy]
  resources :feeds, :only => [:create]
  get 'home/index'
  root :to => 'home#index'
  match '/auth/facebook/callback' => 'sessions#create'
  match 'signout' => 'sessions#destroy', :as => :signout
  get 'show_feed_list', to: 'userfeeds#show_feed_list'
  get 'mark_feed_viewed', to: 'userfeeds#mark_feed_viewed'
  get 'mark_feed_unread', to: 'userfeeds#mark_feed_unread'
  get 'refresh_feed_list', to: 'userfeeds#refresh_feed_list'
  get 'remove_feed', to: 'userfeeds#remove_feed'
  get 'get_read_posts', to: 'userfeeds#get_read_posts'
  get 'get_unread_posts', to: 'userfeeds#get_unread_posts'
end

app/models/feed.rb
require 'time'

class Feed < ActiveRecord::Base
  validates_presence_of :feed_url
  attr_accessible :feed_name, :feed_url, :id, :category
  has_many :userfeed, :dependent => :destroy
  has_many :readfeeditems, :dependent => :destroy
  has_many :feeditems, :dependent => :destroy
  validates_uniqueness_of :feed_url

  # This method updates the feed list of a particular user by fetching new posts of that feed.
  #
  # * *Args*    :
  #   - +userid+ -> The user id of the currently logged in user.
  # * *Returns* :
  #   - nil if user has no feeds.
  # * *Raises* :
  #   None
  #
  def self.update_user_feeds(userid)
    Rails.logger.info "performing the userfeed update of #{userid.to_s}"
    #querying the list of feeds of the user
    feeds = Feed.joins(:userfeed).where('userfeeds.user_id' => userid)
    return true if feeds.nil?

    #populating a list of feedid and url tuples
    feed_id_list =[]

    feeds.entries.each do |entry|
      feed_id_list.append([entry.id, entry.feed_url])
    end

    feed_id_list.each do |entity|
      id = entity[0]
      url = entity[1]
      #querying the published date of the recent post item
      last_entry = Feeditem.where('feed_id' => id).first.post_pub_date
      #fetching the feed
      fetched_feed = Feedzirra::Feed.fetch_and_parse(url)
      #if fetching feed is sucessful
      unless fetched_feed.nil?
        fetched_feed.entries.each do |entry|
          # some feeds puts description in content and others put it in content
          if entry.content.nil?
            postbody = entry.summary
          else
            postbody = entry.content
          end
          #if there are new post, they will be added to Feeditem table
          if entry.published.to_time > last_entry
            Feeditem.create(:feed_id => id, :post_title => entry.title, :post_pub_date => entry.published, :post_body => postbody, :post_url => entry.url)
          end
        end #end of fetched_feed loop
      end #end of unless clause
    end #end of feed_id_list loop
  end

  #end of userfeedupdate

  # This method adds a new feed to the application. If the feed already exists, it just creates a reference to the
  # user by creating a new new entry in userfeeds table.
  #
  # * *Args*    :
  #   - +f_url+     -> The url of the feed. This can be a link to xml file.
  #   - +userid+    -> The user id of the currently logged in user.
  #   - +category+  -> Category of the feed.
  # * *Returns* :
  #   - Errors if fetching feed or creation Feed table entry fail. Returns a notice if user tries to add duplicate feed. Otherwise will return a success message
  # * *Raises* :
  #   None
  #
  def self.add_feed(f_url, userid, category)
    #fetching feed from remote server 
    feed_exist = Feed.find_by_feed_url(f_url)
    if feed_exist.nil?
      fetched_feed = Feedzirra::Feed.fetch_and_parse(f_url)
    else
      fetched_feed = feed_exist
    end

    if fetched_feed.nil?
      return {alert: 'Error occured while fetching feed. Please try again later.'}
    else
      # is_feed_exisits = check_if_feed_exists_by_feed_url(fetched_feed.feed_url)
      if feed_exist
        userfeed_exist = Userfeed.find_by_user_id_and_feed_id(userid, feed_exist.id)
        unless userfeed_exist.nil?
          return {notice: 'You have already added that feed'}
        end
        feed = feed_exist
      else

        feed = Feed.create(:feed_name => fetched_feed.title, :feed_url => fetched_feed.feed_url)
        if feed.nil?
          return {alert: 'Error occured while creating feed. Please try again later.'}
        end

        fetched_feed.entries.each do |entry|
          if entry.content.nil?
            postbody = entry.summary.html_safe
          else
            postbody = entry.content.html_safe
          end
          Feeditem.create(:feed_id => feed.id, :post_title => entry.title, :post_pub_date => entry.published, :post_body => postbody, :post_url => entry.url)
        end

      end

      user = User.find_by_uid(userid)
      Userfeed.create(:user_id => user.uid, :category => category, :feed_id => feed.id)

      return {notice: 'Feed added Successfully'}
    end #end of fetchedfeed.nil?
  end

  # This method queries the subscriptions(feeds) for a given user (ordered)
  #
  # * *Args*    :
  #   - +userid+ -> The user id of the currently logged in user.
  # * *Returns* :
  #   - Array of Feeds, if any in the ascending order of the feed_name attribute
  # * *Raises* :
  #   None
  #
  def self.ordered_feed_list(userid)
    Feed.joins(:userfeed).where('userfeeds.user_id' => userid).order('feed_name ASC')
  end

  # This method queries the subscriptions(feeds) for a given user (unordered)
  #
  # * *Args*    :
  #   - +userid+ -> The user id of the currently logged in user.
  # * *Returns* :
  #   - Array of Feeds, if any in particularly no order
  # * *Raises* :
  #   None
  #
  def self.unordered_feed_list(userid)
    Feed.joins(:userfeed).where('userfeeds.user_id' => userid)
  end

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController

  def create
    feed = params[:feed]

    feed_url = feed[:feed_url]
    category = feed[:category]
    userid = current_user.uid

    returned_message_hash = Feed.add_feed(feed_url, userid,category)
    message_type = returned_message_hash.keys[0]
    flash[message_type] = returned_message_hash[message_type]

    redirect_to userfeeds_path
  end

end

app/views/feeds/_index.html.haml
%div.row{'id' => 'addfeedbutton'}
  %button.btn.btn-primary{'type' => 'button', 'data-toggle' => 'modal', 'data-target' => '#addfeedmodel'}
    %i.icon-plus
    New Feed
  %a.btn.btn-default.pull-right{'href'=> refresh_feed_list_path,'data-remote' => 'true','id'=>'btn-refresh-feed'}
    %i.icon-refresh
%div.row
  %br
  %div{'id' => 'masterfeedcontainer'}
    %div{'id' => 'feedcontainer'}
      %div.row{'id' => 'addfeedbutton'}
        %div.list-group{'id' => 'listgroup'}
          - if @feeditems.nil?
            %p No subscriptions available
          - else
            - @feeditems.each do |feeditem|
              %li.list-group-item
                = link_to feeditem.feed_name.to_s, show_feed_list_path(:feed_id => feeditem.id), remote: true
                %span.badge
                  = @unread_count_hash[feeditem.id].to_s
                

        :javascript
          $("#listgroup").on("click", "li:not(.active)", function ( event ) {
            $(".active", event.delegateTarget).removeClass("active");
            $(this).addClass("active");
            $(".ajax-progress").show();
          });
          $("#btn-refresh-feed").click(function() {
          // Show Progress Indicator
          $(".ajax-progress").show();
          });

        
  

app/views/feeds/_new.html.haml
%div.modal.fade{'id' => 'addfeedmodel','tabindex' => '-1','role' => 'dialog', 'aria-labled by' => 'myModalLabel', 'aria-hidden' => "true"}
  %div.modal-dialog
    %div.modal-content
      %div.modal-header
        %button.close{'type' => 'button', 'data-dismiss' => 'modal', 'aria-hidden' => 'true'} &times;
        %h4.modal-title Add a new feed
      = simple_form_for(@feed, :html => {:class => 'form-horizontal'}) do |f|
        %div.modal-body
          = f.input :feed_url, required: true, label: 'Enter Feed URL', :input_html => { :class => 'form-control' }
          = f.input :category, required: true, label: 'Feed Category', :input_html => {value: 'default',
          :class => 'form-control'}
        %div.modal-footer
          = f.button :submit, 'Add Feed', :class => 'btn-primary form-control'