config/routes.rb
Sapphire::Application.routes.draw do
  #resources :feeditems , :only => [:new, :create]
  resources :userfeeds, :only => [:refresh_feed_list,:remove_feed,:show_feed_list,:mark_feed_viewed,
                                  :mark_feed_unread,:index,:destroy]
  resources :feeds, :only => [:create]
  get 'home/index'
  root :to => 'home#index'
  match '/auth/facebook/callback' => 'sessions#create'
  match 'signout' => 'sessions#destroy', :as => :signout
  get 'show_feed_list', to: 'userfeeds#show_feed_list'
  get 'mark_feed_viewed', to: 'userfeeds#mark_feed_viewed'
  get 'mark_feed_unread', to: 'userfeeds#mark_feed_unread'
  get 'refresh_feed_list', to: 'userfeeds#refresh_feed_list'
  get 'remove_feed', to: 'userfeeds#remove_feed'
  get 'get_read_posts', to: 'userfeeds#get_read_posts'
  get 'get_unread_posts', to: 'userfeeds#get_unread_posts'
end

app/models/userfeed.rb
class Userfeed < ActiveRecord::Base
  belongs_to :user
  belongs_to :feed
  has_many :readfeeditems, :dependent => :destroy
  attr_accessible :category, :user_id, :id, :feed_id

  # This method returns the userfeeds entries and corresponding feeds entries for a particular user.
  #
  # * *Args*    :
  #   - +user_id+  -> id of the currently logged in user
  # * *Returns* :
  #   - userfeeds list and feeds list.
  # * *Raises* :
  #   None
  #
  def self.get_userfeed_with_feed(user_id)
    return Userfeed.where('user_id' => user_id), Feed.unordered_feed_list(user_id)
  end
end

app/controllers/userfeeds_controller.rb
class UserfeedsController < ApplicationController
  before_filter :prepare_userfeed_form, only: [:index]

  def prepare_userfeed_form
    @feed = Feed.new
    @feeditems = Feed.ordered_feed_list(current_user.uid)
    @unread_count_hash = Feeditem.get_unread_post_count(current_user.uid)
  end

  def refresh_feed_list
    Delayed::Job.enqueue UpdateFeed.new(current_user.uid)
    @ajax_status = 'Updating all feeds in the background...'
    respond_to do |format|
      format.js { render 'shared/ajax-progress' }
    end

  end

  def remove_feed
    @userfeed_all, @feedlist_unordered = Userfeed.get_userfeed_with_feed(current_user.uid)
  end

  def show_feed_list
    feed_id = params[:feed_id]
    @readfeeditem_list, @feeditem_list = Feeditem.get_all_posts(current_user.uid, feed_id, max_post_size, 0)
    @feed_id = feed_id
    @max_post_size = max_post_size
    if @feeditem_list.nil? and @readfeeditem_list.nil?
      @ajax_status = 'Error occured while fetching post list. Please try again...'
    end

    respond_to do |format|
      format.js
    end

  end

  def get_unread_posts
    offset = params[:read_page]
    @feed_id = params[:feed_id]
    @unread_posts = Feeditem.get_unread_post_list(current_user.uid, @feed_id, max_post_size, offset)
    @max_post_size = max_post_size
  end

  def get_read_posts
    offset = params[:read_page]
    @feed_id = params[:feed_id]
    @read_posts = Feeditem.get_read_post_list(current_user.uid, @feed_id, max_post_size, offset)
    @max_post_size = max_post_size
  end


  def mark_feed_viewed
    feed_id = params[:feed_id]
    post_id = params[:post_id]
    @ajax_status = Readfeeditem.mark_as_viewed(current_user.uid, feed_id, post_id)
    respond_to do |format|
      format.js { render 'shared/ajax-progress' }
    end

  end

  def mark_feed_unread
    feed_id = params[:feed_id]
    post_id = params[:post_id]
    @ajax_status = Readfeeditem.mark_as_unread(current_user.uid, feed_id, post_id)
  end


  def index

  end

  def destroy
    @userfeed = Userfeed.find(params[:id])
    if @userfeed.destroy
      flash[:notice] = 'Feed removed successfully'
    else
      flash[:alert] = 'An error occured while removing the feed. Please try again.'
    end
    redirect_to remove_feed_path
  end
end

app/views/userfeeds/_morepost.html.haml
= render partial: 'feeditems/post', locals: {feeditem_lst: @read_posts, viewed: true}

app/views/userfeeds/_moreunreadpost.html.haml
= render partial: 'feeditems/post', locals: {feeditem_lst: @unread_posts, viewed: false}

app/views/userfeeds/get_read_posts.js.haml
$(".ajax-progress").hide()
- if @read_posts.size < @max_post_size
  $("#btn-readposts").hide()
$('#readpostsconatiner').append("#{j(render('userfeeds/morepost'))}")

app/views/userfeeds/get_unread_posts.js.haml
$(".ajax-progress").hide()
- if @unread_posts.size < @max_post_size
  $("#btn-unreadposts").hide()
$('#unreadpostscontainer').append("#{j(render('userfeeds/moreunreadpost'))}")

app/views/userfeeds/index.html.haml
%div.container
  %div.row.row-offcanvas.row-offcanvas-right
    %div.col-xs-12.col-sm-9
      %p.pull-right.visible-xs
        %button.btn.btn-primary{'type' => 'button', 'data-toggle' => 'offcanvas'}
          %i.icon-exchange
      %div{'id' => 'masterfeedlistcontainer'}
        %div{'id' => 'feedlistcontainer'}
          = render partial: 'feeditems/index'
    %div.col-xs-6.col-sm-3.sidebar-offcanvas{'id' => 'sidebar', 'role' => 'navigation'}
      = render partial: 'feeds/index'


= render partial: 'feeds/new'

app/views/userfeeds/remove_feed.html.haml
%table{:class=> 'table table-hover'}
  %thead
    %tr
      %th Feed Title
      %th Category
      %th Created Date
      %th Remove
  %tbody
    - @userfeed_all.each_with_index do |feed,index|
      %tr
        %td= @feedlist_unordered[index].feed_name
        %td= feed.category
        %td= feed.created_at
        %td= button_to 'Remove', userfeed_path(feed), :method => :delete, :confirm => 'Feed will be removed. Are you sure?', :class => 'btn btn-danger btn-xs'

app/views/userfeeds/show_feed_list.js.haml
$(".ajax-progress").hide()
- if !@ajax_status.nil?
  $(".modal-body > p").text("#{@ajax_status}")
  $("#ajax-status").modal("show");
- else
  $('#feedlistcontainer').html("#{j(render('feeditems/index'))}")