config/routes.rb
Sapphire::Application.routes.draw do
  #resources :feeditems , :only => [:new, :create]
  resources :userfeeds, :only => [:refresh_feed_list,:remove_feed,:show_feed_list,:mark_feed_viewed,
                                  :mark_feed_unread,:index,:destroy]
  resources :feeds, :only => [:create]
  get 'home/index'
  root :to => 'home#index'
  match '/auth/facebook/callback' => 'sessions#create'
  match 'signout' => 'sessions#destroy', :as => :signout
  get 'show_feed_list', to: 'userfeeds#show_feed_list'
  get 'mark_feed_viewed', to: 'userfeeds#mark_feed_viewed'
  get 'mark_feed_unread', to: 'userfeeds#mark_feed_unread'
  get 'refresh_feed_list', to: 'userfeeds#refresh_feed_list'
  get 'remove_feed', to: 'userfeeds#remove_feed'
  get 'get_read_posts', to: 'userfeeds#get_read_posts'
  get 'get_unread_posts', to: 'userfeeds#get_unread_posts'
end

app/models/feeditem.rb
class Feeditem < ActiveRecord::Base
  belongs_to :feed
  has_many :readfeeditems, :dependent => :destroy
  attr_accessible :post_title, :post_pub_date, :post_body, :post_url, :feed_id, :id
  validates_uniqueness_of :post_url, :scope => [:feed_id]

  # This method returns the viewed feeditems (posts) of a feed for a particular user.
  #
  # * *Args*    :
  #   - +feed_id+ -> id of the feed where the feeditems belong to
  #   - +user_id+  -> The id of the currently logged in user
  #   - +limit+   -> Number of feeditems to return (e:g. 10 )
  #   - +offset+  -> Starting postition of the returned results (e:g limit of 12 and offset of 3 will return results
  # from 36th (3*12) item onwards excluding 36th item)
  # * *Returns* :
  #   - List of Feeditems or nil.
  # * *Raises* :
  #   None
  #
  def self.get_read_post_list(user_id, feed_id, limit, offset)
    Feeditem.joins(:readfeeditems).where('readfeeditems.user_id = (?) AND readfeeditems.feed_id = (?) ', user_id,
                                         feed_id).order('post_pub_date DESC').limit(limit).offset(offset.to_i*
                                                                                                      limit.to_i)
  end

  # This method returns the unviewed feeditems (posts) of a feed for a particular user.
  #
  # * *Args*    :
  #   - +feed_id+ -> id of the feed where the feeditems belong to
  #   - +user_id+  -> The id of the currently logged in user
  #   - +limit+   -> Number of feeditems to return (e:g. 10 )
  #   - +offset+  -> Starting postition of the returned results (e:g limit of 12 and offset of 3 will return results
  # from 36th (3*12) item onwards excluding 36th item)
  # * *Returns* :
  #   - List of Feeditems or nil.
  # * *Raises* :
  #   None
  #
  def self.get_unread_post_list(user_id, feed_id, limit, offset)
    statement = "LEFT OUTER JOIN readfeeditems ON readfeeditems.feeditem_id=feeditems.id and readfeeditems.user_id =#{user_id.to_s}"
    Feeditem.joins(statement).where('readfeeditems.id is null and feeditems.feed_id=(?)',
                                    feed_id).order('post_pub_date DESC').limit(limit).offset(offset.to_i*
                                                                                                 limit.to_i)
  end

  # This method returns the number of unviewed feeditems (posts) of all the feeds for a particular user.
  #
  # * *Args*    :
  #   - +user_id+  -> The id of the currently logged in user
  # * *Returns* :
  #   - Hash with the feed id as the key and number of unread posts count as the value.
  # * *Raises* :
  #   None
  #
  def self.get_unread_post_count(user_id)
    statement = "LEFT OUTER JOIN readfeeditems ON readfeeditems.feeditem_id=feeditems.id and readfeeditems.user_id =#{user_id.to_s}"
    Feeditem.joins(statement).where('readfeeditems.id is null').group('feeditems.feed_id').count()
  end

  # This method returns viewed feeditems and unviewed feeditems of a feed for a particular user.
  #
  # * *Args*    :
  #   - +feed_id+ -> id of the feed where the feeditems belong to
  #   - +user_id+ -> The id of the currently logged in user
  #   - +limit+   -> Number of feeditems to return (e:g. 10 )
  #   - +offset+  -> Starting postition of the returned results (e:g limit of 12 and offset of 3 will return results
  # from 36th (3*12) item onwards excluding 36th item)
  # * *Returns* :
  #   - Two lists of feeditems. Unread feeditems and Read feeditems.l
  # * *Raises* :
  #   None
  #
  def self.get_all_posts(user_id, feed_id, limit, offset)
    return Feeditem.get_read_post_list(user_id, feed_id, limit, offset), Feeditem.get_unread_post_list(user_id,
                                                                                                       feed_id, limit,
                                                                                                       offset)
  end
end

app/controllers/feeditems_controller.rb
class FeeditemsController < ApplicationController

end

app/views/feeditems/_index.html.haml
%div.panel-group{'id' => 'accordion'}
  - if @feeditem_list.nil?
    %p
  - else
    %div{'id' => 'unreadpostscontainer'}
      = render partial: 'feeditems/post', locals: {feeditem_lst: @feeditem_list, viewed: false}
    - if @feeditem_list.size < @max_post_size
      :javascript
        $('#btn-unreadposts').hide()
    %div{'id' => 'btn-unreadposts-container'}
      %a{'id'=>'btn-unreadposts', 'class' => 'btn btn-default btn-xs'} More Unread Posts
    :javascript
      var unreadpost=0
      $('#btn-unreadposts').click(function() {
        $(".ajax-progress").show();
        unreadpost++
        $.get('get_unread_posts',{feed_id: #{@feed_id}, read_page: unreadpost});

       });


  - if @readfeeditem_list.nil?
    %p
  - else
    %div{'id' => 'readpostsconatiner'}
      = render partial: 'feeditems/post', locals: {feeditem_lst: @readfeeditem_list, viewed: true}
    - if @readfeeditem_list.size < @max_post_size
      :javascript
        $('#btn-readposts').hide()
    %div{'id' => 'btn-unreadposts-container'}
      %a{'id'=>'btn-readposts','class' => 'btn btn-default btn-xs'} More Viewed Posts
    :javascript
      var readpost=0
      $('#btn-readposts').click(function() {
        $(".ajax-progress").show();
        readpost++
        $.get('get_read_posts',{feed_id: #{@feed_id}, read_page: readpost});
       });

app/views/feeditems/_post.html.haml
- #noinspection RubyStringKeysInHashInspection
- feeditem_lst.each do |feeditem|
  - $item_id = feeditem.id
  - $item_title = feeditem.post_title
  - $item_url = feeditem.post_url
  %div.panel-group{'id' => 'accordion'}
    %div.panel.panel-default{'id' => "panel#{$item_id}"}
      - if viewed
        %div.panel-heading-read{'id' => "panelhead#{$item_id}"}
          %h4.panel-title
            %a.accordion-toggle{'data-toggle' => 'collapse', 'data-parent' => '#accordion', 'href' => "#feed#{$item_id}", 'id' => "acclink#{$item_id}"}
              = feeditem.post_title
      - else
        %div.panel-heading{"id" => "panelhead#{$item_id}"}
          %h4.panel-title
            %a.accordion-toggle{'data-toggle' => 'collapse', 'data-parent' => '#accordion', 'href' => "#feed#{$item_id}", 'id' => "acclink#{$item_id}"}
              = feeditem.post_title
      %div.panel-collapse.collapse{'id' => "feed#{$item_id}"}
        %div.panel-body
          .row{'id' => 'posttoolbar'}
            %div.btn-toolbar
              %div.btn-group
                %p{'id'=>'published'}= 'Posted on: '+ feeditem.post_pub_date.to_s
              %div.btn-group.pull-right
                %a.btn.btn-default{'id' => 'openoriginal','href'=> feeditem.post_url, 'target'=>'_blank'}
                  %i.icon-external-link
                %button.btn.btn-default{'id' => "fullbtn#{$item_id}"}
                  %i.icon-fullscreen
              %div.btn-group.pull-right
                = link_to 'Mark as Unread', mark_feed_unread_path(:feed_id => @feed_id, :post_id => feeditem.id),
                :type => 'button', :id => "btn#{$item_id}",:class =>'btn btn-default btn-sm', remote: true
              %div.btn-group.pull-right
                %button.btn.btn-default{'type' => 'default','onClick' => "window.open('http://www.facebook.com/share.php?u=#{$item_url}','Share on Facebook', 'toolbar=no, scrollbars=yes, width=500, height=400');"}
                  %i.icon-facebook
                %button.btn.btn-default{'type' => 'default','onClick' => "window.open('http://twitter.com/intent/tweet?source=tweetbutton&text=#{$item_title}&url=#{$item_url}', 'Share on Twitter', 'toolbar=no, scrollbars=yes, width=500, height=400');"}
                  %i.icon-twitter
          .row.post-body{'id' => "postbody#{$item_id}"}
            - unless feeditem.post_body.nil?
              %p= feeditem.post_body.html_safe

      :javascript

        $('#acclink#{$item_id}').click(function() { $.get('mark_feed_viewed',{feed_id: #{@feed_id}, post_id: #{$item_id}}); });
        $('#acclink#{$item_id}').click(function() {
            if($("#panelhead#{$item_id}").hasClass("panel-heading"))
              $("#panelhead#{$item_id}").removeClass("panel-heading").addClass("panel-heading-read");;

            } ) ;
        $('#btn#{$item_id}').click(function() {
        $('#acclink#{$item_id}').collapse('toggle');
            if($("#panelhead#{$item_id}").hasClass("panel-heading-read"))
              $("#panelhead#{$item_id}").removeClass("panel-heading-read").addClass("panel-heading");;
         });
        $('#fullbtn#{$item_id}').click(function(e){
          $('#postbody#{$item_id}').fullScreen(
            {
              'background':'#ffffff'
            });
          e.preventDefault();
        });